version: "3.9"
services:
  galesburg_eats_client:
    container_name: galesburg_eats_client
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - '.:/app'
      - '/app/node_modules'
    ports:
      - "8080:8080"